from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# === Step 1: Load YOLOv8 model ===
checkpoint_path = 'C:/Users/Haiqal/Desktop/PRBX/YOLOv8_Implementation/runs/yolov8_fish4k_train/weights/last.pt' # Path to your last checkpoint (autogenerated by YOLO)
model = YOLO(checkpoint_path)  # Uncomment this line to load from checkpoint

# Choose model size: yolov8n.pt, yolov8s.pt, yolov8m.pt, etc.
# model = YOLO('yolov8n.pt')  

def train():
    # === Step 2: Train the model ===
    # You can adjust the number of epochs, image size, batch size, etc.
    model.train(
        resume=True,                   # Set to True to resume training from last checkpoint
        data='datasets/Fish4K-YOLO/data.yaml',  # Path to your dataset config
        epochs=50,                     # Number of training epochs
        imgsz=640,                     # Image size (YOLO default is 640x640)
        batch=16,                      # Adjust based on your hardware
        device = 0,                    # Use GPU (0 for first GPU, 1 for second, etc.)
        project='runs',                # Output folder
        name='yolov8_fish4k_train',    # Custom name for this run
        exist_ok=True                  # Overwrite if folder already exists
    )

def eval():
    # === Step 3: Validate on test set ===
    results = model.val(
        data='C:/Users/Haiqal/Desktop/PRBX/datasets/Fish4K-YOLO/data.yaml', 
        split='test',
        project='runs',
        name='yolov8_fish4k_eval'
    )  # Automatically uses best.pt from training
    
    # Extract and unpack all four  metrics
    precision, recall, map50, map50_95 = results.box.mean_results()

    # Compute F1-score from averaged precision and recall
    f1_score = 2 * (precision * recall) / (precision + recall + 1e-8)

    # Create DataFrame and save to CSV
    df = pd.DataFrame([{
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1_score,
        "mAP@0.5": map50,
        "mAP@0.5:0.95": map50_95
    }])

    df.to_csv("yolov8_evaluation_summary.csv", index=False)
    print("Metrics saved to yolov8_evaluation_summary.csv")

def predict():
    # === Step 4: Inference on test set ===
    model.predict(
        source='C:/Users/Haiqal/Desktop/PRBX/datasets/Fish4K-YOLO/images/test',  # Folder of test images
        save=True,                         # Save results to output folder
        save_txt=True,                     # Also save bounding box text files
        project='runs',                    # Output folder
        name='yolov8_fish4k_infer',        # Inference run name
        exist_ok=True
    )

def metric_visualization():
    # === CONFIG ===
    CSV_PATH = "runs/yolov8_fish4k_train/results.csv"  # Change as needed
    sns.set_theme(style="whitegrid")

    # === Load Data ===
    df = pd.read_csv(CSV_PATH)

    # === Load Data ===
    df = pd.read_csv(CSV_PATH)

    # === Plot 1: Training Losses ===
    plt.figure(figsize=(10, 6))
    plt.plot(df['epoch'], df['train/box_loss'], label='Box Loss')
    plt.plot(df['epoch'], df['train/cls_loss'], label='Class Loss')
    plt.plot(df['epoch'], df['train/dfl_loss'], label='DFL Loss')
    plt.title('Training Losses over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss Value')
    plt.legend()
    plt.tight_layout()
    plt.savefig('losses_plot.png')
    plt.show()

    # === Plot 2: Validation Losses ===
    plt.figure(figsize=(10, 6))
    plt.plot(df['epoch'], df['val/box_loss'], label='Val Box Loss')
    plt.plot(df['epoch'], df['val/cls_loss'], label='Val Class Loss')
    plt.plot(df['epoch'], df['val/dfl_loss'], label='Val DFL Loss')
    plt.title('Validation Losses over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss Value')
    plt.legend()
    plt.tight_layout()
    plt.savefig('val_losses_plot.png')
    plt.show()

    # === Plot 3: Precision and Recall ===
    plt.figure(figsize=(10, 6))
    plt.plot(df['epoch'], df['metrics/precision(B)'], label='Precision (B)')
    plt.plot(df['epoch'], df['metrics/recall(B)'], label='Recall (B)')
    plt.title('Precision and Recall over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Score')
    plt.legend()
    plt.tight_layout()
    plt.savefig('precision_recall_plot.png')
    plt.show()

    # === Plot 4: mAP@0.5 and mAP@0.5:0.95 ===
    plt.figure(figsize=(10, 6))
    plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@0.5')
    plt.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@0.5:0.95')
    plt.title('Mean Average Precision over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Score')
    plt.legend()
    plt.tight_layout()
    plt.savefig('map_plot.png')
    plt.show()

    # === Plot 5: Learning Rates (optional) ===
    plt.figure(figsize=(10, 6))
    plt.plot(df['epoch'], df['lr/pg0'], label='LR pg0')
    plt.plot(df['epoch'], df['lr/pg1'], label='LR pg1')
    plt.plot(df['epoch'], df['lr/pg2'], label='LR pg2')
    plt.title('Learning Rates over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Learning Rate')
    plt.legend()
    plt.tight_layout()
    plt.savefig('learning_rates_plot.png')
    plt.show()

if __name__ == '__main__':
    # train()
    metric_visualization()
    # predict()
    eval()